export const filters = {
    genres: [
        { value: "All", label: "All genre" },
        { value: "Action", label: "Action" },
        { value: "Adventure", label: "Adventure" },
        { value: "Animation", label: "Animation" },
        { value: "Biography", label: "Biography" },
        { value: "Comedy", label: "Comedy" },
        { value: "Crime", label: "Crime" },
        { value: "Documentary", label: "Documentary" },
        { value: "Drama", label: "Drama" },
        { value: "Family", label: "Family" },
        { value: "Fantasy", label: "Fantasy" },
        { value: "Film-Noir", label: "Film-Noir" },
        { value: "History", label: "History" },
        { value: "Horror", label: "Horror" },
        { value: "Music", label: "Music" },
        { value: "Musical", label: "Musical" },
        { value: "Mystery", label: "Mystery" },
        { value: "News", label: "News" },
        { value: "Romance", label: "Romance" },
        { value: "Sci-Fi", label: "Sci-Fi" },
        { value: "Short", label: "Short" },
        { value: "Sport", label: "Sport" },
        { value: "Talk-Show", label: "Talk-Show" },
        { value: "Thriller", label: "Thriller" },
        { value: "War", label: "War" },
        { value: "Western", label: "Western" },
    ],
    rating: [
        { value: "All", label: "All" },
        { value: "9", label: "9+" },
        { value: "8", label: "8+" },
        { value: "7", label: "7+" },
        { value: "6", label: "6+" },
    ],
    sortby: [
        { value: "default", label: "Default" },
        { value: "title", label: "Name" },
        { value: "released", label: "Year" },
        { value: "imdb.rating", label: "Imdb" },
    ],
};
